name: Daily Developer Activity (IST Based)

permissions:
  contents: write

on:
  schedule:
    - cron: '0 7 * * *'   # 12:30 PM IST
    - cron: '43 9 * * *'  # 3:13 PM IST
    - cron: '17 12 * * *' # 5:47 PM IST
    - cron: '3 14 * * *'  # 7:33 PM IST
    - cron: '30 16 * * *' # 10:00 PM IST
    - cron: '56 18 * * *' # 12:26 AM IST (next day)
    - cron: '11 21 * * *' # 2:41 AM IST
    - cron: '39 23 * * *' # 5:09 AM IST
  workflow_dispatch:

jobs:
  simulate-coding:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Simulated Task
        run: |
          mkdir -p task-logs
          FILE="task-logs/$(date '+%Y-%m-%d')-$(date '+%H%M').md"
          TASKS=("Refactored legacy code"
                 "Implemented new feature"
                 "Debugged authentication issue"
                 "Wrote unit tests for module"
                 "Updated project documentation"
                 "Improved API error handling"
                 "Optimized performance of loop"
                 "Analyzed code coverage results"
                 "Fixed UI responsiveness bug")

          RANDOM_TASK=${TASKS[$RANDOM % ${#TASKS[@]}]}
          echo "# Dev Task - $(date -d '+5 hours 30 minutes')" > "$FILE"
          echo "$RANDOM_TASK" >> "$FILE"
          echo "- Time: $(date -d '+5 hours 30 minutes' '+%H:%M:%S')" >> "$FILE"
          echo "- Notes: This was a key improvement step." >> "$FILE"

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'Master054439'
          git config --global user.email 'kundankumarjaiswal05@gmail.com'
          git add task-logs/
          git commit -m "💻 Dev Activity: $(date -d '+5 hours 30 minutes' '+%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push
