name: Generate Daily Commit

permissions:
  contents: write  # ✅ This allows the action to push changes

on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update Date File
        run: echo "Last updated on $(date)" > update.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'Master054439'
          git config --global user.email 'kundankumarjaiswal05@gmail.com'
          git add update.txt
          git commit -m "Daily contribution $(date)" || echo "No changes to commit"
          git push
